import os


configfile: "config/config.yaml"


DEFAULT_ENV = "../envs/env.yaml"
REF = config["ref"]
FAI = f"{REF}.fai"
LEVIO_EXE = config["levio_exe"]
#LEVIO_INDEX = config["levio_index"]
LEVIO_CHAIN = config["levio_chain"]
DSA = config["dsa"]
SAMPLES = config["inputs"].keys()
MAX_THREADS = config.get("max_threads", 40)
SORT_THREADS = min(MAX_THREADS, 16)


include: "rules/levio.smk"


wildcard_constraints:
    sm="|".join(SAMPLES),


rule all:
    input:
        expand(rules.leviosam2_sorted.output, sm=SAMPLES),
