import os


configfile: "config/config.yaml"


DEFAULT_ENV = "../envs/env.yaml"
REF = config["ref"]
LEVIO_EXE = config["levio_exe"]
LEVIO_INDEX = config["levio_index"]
DSA = config["dsa"]
SAMPLES = config["inputs"].keys()
MAX_THREADS = config.get("max_threads", 32)
SORT_THREADS = min(MAX_THREADS, 16)

include: "rules/levio.smk"


wildcard_constraints:
    sm="|".join(SAMPLES),


rule all:
    input:
        expand(rules.leviosam2_sorted.output, sm=SAMPLES),
