rerun-incomplete: True
show-failed-logs: True
printshellcmds: True
rerun-triggers: mtime
restart-times: 0
software-deployment-method:
  - apptainer
  - conda
cores: 32
local-cores: 4
default-resources:
  - disk_mb=4096
  - mem_mb=16096
  - runtime=600
